### PR TITLE
importer: fix tar and 7z archive import

### LINKED ISSUE #5664: Tarfile import fails with extraction failed: 'TarFile' object has no attribute 'infolist'
Seems `TarFile.infolist` was removed in Python 3: https://github.com/python/cpython/issues/47289#issuecomment-1093424447 when `ZipFileCompat` was removed from `TarFile`

introduced in https://github.com/beetbox/beets/pull/4396

### Problem

Running this command in verbose (`-vv`) mode:

```sh
beet -vv import -m Elton\ John\ -\ Your\ Songs\ \(1985\)\ \(flac\).tar-xpost/Elton_John_-_Your_Songs_\(1985\)_\(flac\).tar
```

Led to this problem:

```
user configuration: /home/bcotton/.config/beets/config.yaml
data directory: /home/bcotton/.config/beets
plugin paths:
library database: /media/music/musiclibrary.db
library directory: /media/music/curated
Sending event: library_opened
Sending event: import_begin
Extracting archive: /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
extraction failed: 'TarFile' object has no attribute 'infolist'
No files imported from /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux
* Python version: Python 3.12.8
* beets version:  master as of 2025-03-11
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: /media/music/curated
id3extract:
    mappings:
        WOAS: spotify_track_id

import:
    copy: yes
    move: no
# --------------- Main ---------------

library: /media/music/musiclibrary.db
musicbrainz:
    enabled: yes
    external_ids:
        bandcamp: yes
        beatport: yes
        deezer: yes
        discogs: yes
        spotify: yes
        tidal: yes
        youtube: yes
    extra_tags: []
    genres: yes
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1
    searchlimit: 5

# --------------- Plugins ---------------

plugins:
- spotify
- info
- fetchart
- lyrics
- lastgenre
- id3extract
spotify:
    mode: open
    region_filter: US
    show_failures: 'on'
    source_weight: 0
    tiebreak: first
    artist_field: albumartist
    album_field: album
    track_field: title
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: no
    keep_existing: no
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
lyrics:
    auto: yes
    translate:
        api_key: REDACTED
        from_languages: []
        to_language:
    dist_thresh: 0.11
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    print: no
    synced: no
    sources:
    - lrclib
    - google
    - genius
    - tekstowo

```

### PR DESCRIPTION
**Pull request by bcotton**
Sorry about the delay.

- Fixes #5664. Both tar and 7z archive imports were broken because `ArchiveImportTask.extract` calls `archive.infolist()`, but neither `tarfile.TarFile` (lost `ZipFileCompat` in Python 3) nor `py7zr.SevenZipFile` (exposes `list()` instead) provides it. Both surfaces produced `'… object has no attribute 'infolist'` and aborted the import.
- Adds thin module-level wrappers — `TarArchive` (subclass of `tarfile.TarFile`) and `SevenZipArchive` (composition over `py7zr.SevenZipFile`, since `py7zr` is optional) — that expose a `ZipFile`-compatible `infolist()`. Tiny `_TarMemberInfo` / `_SevenZipMemberInfo` adapters carry only the two attributes the extract loop reads: `filename` and `date_time`.
- Fixes a latent bug in the test suite: `ImportTarTest.create_archive` and `Import7zTest`'s inheritance were dead code. The parent `test_import_zip` called the module-level `create_archive(self)` helper, which only knows how to build zips, so both tar and 7z tests were silently exercising the zip path. Routing through `self.create_archive()` makes them real regression tests for this bug.

This supersedes #5666; design follows @wisp3rwind's review feedback there (module-level wrappers, minimal adapters, shared test infrastructure via `self.create_archive`).

## Test plan

- [x] `pytest test/test_importer.py::ImportZipTest test/test_importer.py::ImportTarTest test/test_importer.py::Import7zTest` — all pass
- [x] Reverting only `beets/importer/tasks.py` to master while keeping test changes reproduces the original `'TarFile' object has no attribute 'infolist'` and `'SevenZipFile' object has no attribute 'infolist'` errors (confirming the tests are real regression tests)
- [x] `pytest test/test_importer.py` — full module: 127 passed, 5 skipped (env-dependent: reflink, unrar, unimplemented)
- [ ] Manual: `beet import` on a real `.tar` archive

### CODE REVIEW

File: beets/importer/tasks.py [hunk 1]
```diff
@@ -815,19 +815,78 @@ def save_progress(self) -> None:
...
+    def cleanup(self, copy=False, delete=False, move=False):
         pass
 
-    def _emit_imported(self, lib: library.Library) -> None:
+    def _emit_imported(self, lib):
         pass
 
 
-ArchiveHandler = tuple[Callable[[util.StrPath], bool], Callable[..., Any]]
+ArchiveHandler = tuple[
```
Comment (semohr) [inline beets/importer/tasks.py]: Would it make sense to adjust the ArchiveHandler? I.e removeing the `Any` such that we have a early warning system witth mypy in case of future changes to the api? Maybe a Protocol would work?

**Review by semohr — CHANGES_REQUESTED** [review]
Sorry for the delay on our side. Looks good to me. Do you mind rebasing and adjusting the changelog?

Thanks!

**Comment by bcotton** [comment]
done, rebased and addressed your comment.

**Review by semohr — APPROVED** [review]
