### PR TITLE
fix(hooks): chain original error when cached_property AttrDict lookup fails (#6558)

### LINKED ISSUE #6558: Beet Import Crash: AttributeError
### Problem: 2.10.0 regression from 2.9.0 — import crash (TrackInfo.raw_data missing)

Running this command in verbose (`-v`) mode:

```sh
$ beet -v import -I "/<path>/<album>"
```

Leads to the following crash:

```
Sending event: import_task_choice
Traceback (most recent call last):
  File "/lsiopy/bin/beet", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  ...
  File "/lsiopy/lib/python3.12/site-packages/beets/autotag/hooks.py", line 492, in merge_with_album
    raw_track = self.raw_data
                ^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/beets/autotag/hooks.py", line 123, in __getattr__
    raise AttributeError(
AttributeError: 'TrackInfo' object has no attribute 'raw_data'
```

The album is successfully matched (100% / Distance: 0.00) before the crash, so the failure occurs during metadata application after selecting the match.

### Setup

* OS: Docker (Linux)
* Python version: 3.12.13
* beets version: 2.10.0
* Turning off plugins made problem go away (yes/no): not tested

My configuration (output of `beet config`) is:

```yaml
# (omitted for brevity — can provide if needed)
```

### Notes

* This workflow worked on 2.9.0.
* The failure occurs during `apply_metadata()` → `merge_with_album()`.
* Workaround: tagging externally (e.g. Picard) and using `beet import -A`.

### PR DESCRIPTION
**Pull request by sarteta**
Fixes #6558.

### Problem
When a `cached_property` on an `AttrDict` subclass raises `AttributeError` during its own computation, Python's attribute lookup falls back to `__getattr__` with the property's own name. That masks the *real* missing field behind a misleading traceback like:

```
AttributeError: 'AlbumInfo' object has no attribute 'raw_data'
```

…even though `raw_data` exists on the instance and the code inside `raw_data` is what blew up on a missing sibling attribute. Users and maintainers hit this both on #6558 and on the earlier #6503 / #6506 reports (different metadata providers, same masking shape).

### Fix
In `AttrDict.__getattr__`, if the looked-up class attribute is a `cached_property`, invoke it explicitly. If it raises `AttributeError`, re-raise as `RuntimeError` with `from exc` so the original cause is preserved on the traceback and names the attribute that actually failed.

Plain missing-attribute behaviour (`obj.nope` on an `AttrDict`) is unchanged — that still raises `AttributeError` as before.

### Tests
Added a regression class `TestAttrDictCachedPropertyMasking` in `test/autotag/test_hooks.py` covering:

1. real missing attr in a `cached_property` body surfaces as `RuntimeError` naming the missing field
2. the `RuntimeError.__cause__` is the original `AttributeError`
3. a plain missing attr on an `AttrDict` still raises `AttributeError`
4. existing dict-key access (`obj.title`) still works

Full `test/autotag/test_hooks.py` suite: 90 passed locally.

### Follow-up
Picked approach (1) from @snejus' comment on #6558 (https://github.com/beetbox/beets/issues/6558#issuecomment-3565413797). Happy to iterate on the exception type or wording.

### CODE REVIEW

File: beets/autotag/hooks.py [hunk 1]
```diff
@@ -120,6 +120,20 @@ def __getattr__(self, attr: str) -> V:
...
+            # computation, Python's attribute lookup falls back to
+            # __getattr__ with the property's own name, masking the real
+            # missing field. Re-raise as RuntimeError chaining the cause
+            # so the traceback names the attribute that actually failed.
+            try:
+                return cls_attr.__get__(self, type(self))
+            except AttributeError as exc:
+                raise RuntimeError(
+                    f"{type(self).__name__}.{attr} computation failed: {exc}"
+                ) from exc
```
[the remark this answers is not in the document]
Comment (snejus) [reply beets/autotag/hooks.py]: maybe grug have point

**Comment by snejus** [comment]
Just tested this:

```
  ...
  File "/home/sarunas/repo/beets/beets/importer/tasks.py", line 264, in apply_metadata
    self.match.apply_metadata()
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 632, in apply_metadata
    for item, data in self.merged_pairs:
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 625, in merged_pairs
    return [
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 626, in <listcomp>
    (i, ti.merge_with_album(self.info))
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 505, in merge_with_album
    album = album_info.raw_data
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 133, in __getattr__
    raise RuntimeError(
RuntimeError: AlbumInfo.raw_data computation failed: 'int' object has no attribute 'lower'
```

Would it be possible to recover the full traceback here to the specific line where this originated from?

**Comment by sarteta** [comment]
yeah good catch. dropping the RuntimeError-wrap-in-__getattr__ approach, moved the cached_property interception into __getattribute__ so the descriptor only runs once (kills the double-invoke @Copilot flagged). on a failure we still have to raise a non-AttributeError to stop python falling back to __getattr__, but the traceback is now re-attached with with_traceback(exc.__traceback__), so the visible frames go all the way down to the line inside the property body where the real lookup blew up. original AttributeError is still available as __cause__. pushed.

**Comment by snejus** [comment]
Nice, much better. Though now we have a sort of a double-traceback here, no?

```
Sending event: import_task_choice
Traceback (most recent call last):
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 137, in __getattribute__
    return descr.__get__(self, type(self))
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 327, in raw_data
    data = {**super().raw_data}
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 209, in raw_data
    return correct_list_fields(data)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 106, in correct_list_fields
    ensure_first_value(*pair)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 87, in ensure_first_value
    single_val_lower = single_val.lower()
AttributeError: 'int' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sarunas/.local/bin/beet", line 8, in <module>
    main()
  File "/home/sarunas/repo/beets/beets/ui/__init__.py", line 1013, in main
    _raw_main(args)
  File "/home/sarunas/repo/beets/beets/ui/__init__.py", line 992, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/sarunas/repo/beets/beets/ui/commands/import_/__init__.py", line 131, in import_func
    import_files(lib, byte_paths, query)
  File "/home/sarunas/repo/beets/beets/ui/commands/import_/__init__.py", line 75, in import_files
    session.run()
  File "/home/sarunas/repo/beets/beets/importer/session.py", line 239, in run
    pl.run_sequential()
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 422, in run_sequential
    list(self.pull())
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 510, in pull
    out = coro.send(msg)
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 196, in coro
    task = func(*args, task)
  File "/home/sarunas/repo/beets/beets/importer/stages.py", line 217, in user_query
    _apply_choice(session, task)
  File "/home/sarunas/repo/beets/beets/importer/stages.py", line 323, in _apply_choice
    task.apply_metadata()
  File "/home/sarunas/repo/beets/beets/importer/tasks.py", line 264, in apply_metadata
    self.match.apply_metadata()
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 644, in apply_metadata
    for item, data in self.merged_pairs:
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 637, in merged_pairs
    return [
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 638, in <listcomp>
    (i, ti.merge_with_album(self.info))
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 517, in merge_with_album
    album = album_info.raw_data
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 139, in __getattribute__
    raise RuntimeError(
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 137, in __getattribute__
    return descr.__get__(self, type(self))
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 327, in raw_data
    data = {**super().raw_data}
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 209, in raw_data
    return correct_list_fields(data)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 106, in correct_list_fields
    ensure_first_value(*pair)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 87, in ensure_first_value
    single_val_lower = single_val.lower()
RuntimeError: AlbumInfo.raw_data failed: 'int' object has no attribute 'lower'
```

**Comment by sarteta** [comment]
yeah that was the with_traceback biting — attaching the inner tb onto the RuntimeError AND chaining via `from exc` made python render the frames twice (once at the cause, once at the outer). dropped `.with_traceback(exc.__traceback__)`: `raise RuntimeError(...) from exc` is enough. python prints the inner traceback once (pointing at the real failing line inside the property body), then 'The above exception was the direct cause of the following exception', then the outer frame at the raise site. tested the same shape (int.lower() inside a cached_property) and now it's a single clean chain. pushed.

File: beets/autotag/hooks.py [hunk 2]
```diff
@@ -116,6 +116,33 @@ def copy(self) -> Self:
...
+                    continue
+                if isinstance(descr, cached_property):
+                    try:
+                        return descr.__get__(self, type(self))
+                    except AttributeError as exc:
+                        raise RuntimeError(
+                            f"{type(self).__name__}.{attr} failed: {exc}"
+                        ) from exc
+                break
+        return super().__getattribute__(attr)
```
Comment (snejus) [inline beets/autotag/hooks.py]: Consider the following:

```suggestion
    def __getattribute__(self, attr: str) -> V:
        # Intercept cached_property failures so an AttributeError raised
        # inside the property body is not masked by __getattr__ fallback.
        # Reuse the original traceback so the wrapped RuntimeError still
        # points at the real failing line, but suppress the printed cause
        # block to keep CLI tracebacks readable. See #6558 (and #6503 /
        # #6506 for the same masking pattern with different metadata
        # providers).
        try:
            return super().__getattribute__(attr)
        except AttributeError as exc:
            if not attr.startswith("__"):
                for klass in type(self).__mro__:
                    descr = klass.__dict__.get(attr)
                    if descr is None:
                        continue
                    if isinstance(descr, cached_property):
                        raise RuntimeError(
                            f"{type(self).__name__}.{attr} failed: {exc}"
                        ).with_traceback(exc.__traceback__) from None
                    break
            raise

```

And see the resulting traceback:

```
Enter search, enter Id, aBort, eDit, edit Candidates? 
Sending event: import_task_choice
Traceback (most recent call last):
  File "/home/sarunas/.local/bin/beet", line 8, in <module>
    main()
  File "/home/sarunas/repo/beets/beets/ui/__init__.py", line 1013, in main
    _raw_main(args)
  File "/home/sarunas/repo/beets/beets/ui/__init__.py", line 992, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/sarunas/repo/beets/beets/ui/commands/import_/__init__.py", line 131, in import_func
    import_files(lib, byte_paths, query)
  File "/home/sarunas/repo/beets/beets/ui/commands/import_/__init__.py", line 75, in import_files
    session.run()
  File "/home/sarunas/repo/beets/beets/importer/session.py", line 239, in run
    pl.run_sequential()
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 422, in run_sequential
    list(self.pull())
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 510, in pull
    out = coro.send(msg)
  File "/home/sarunas/repo/beets/beets/util/pipeline.py", line 196, in coro
    task = func(*args, task)
  File "/home/sarunas/repo/beets/beets/importer/stages.py", line 217, in user_query
    _apply_choice(session, task)
  File "/home/sarunas/repo/beets/beets/importer/stages.py", line 323, in _apply_choice
    task.apply_metadata()
  File "/home/sarunas/repo/beets/beets/importer/tasks.py", line 264, in apply_metadata
    self.match.apply_metadata()
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 641, in apply_metadata
    for item, data in self.merged_pairs:
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 634, in merged_pairs
    return [
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 635, in <listcomp>
    (i, ti.merge_with_album(self.info))
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 514, in merge_with_album
    album = album_info.raw_data
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 136, in __getattribute__
    raise RuntimeError(
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 128, in __getattribute__
    return super().__getattribute__(attr)
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 324, in raw_data
    data = {**super().raw_data}
  File "/home/sarunas/.local/share/uv/python/cpython-3.10.18-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 206, in raw_data
    return correct_list_fields(data)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 106, in correct_list_fields
    ensure_first_value(*pair)
  File "/home/sarunas/repo/beets/beets/autotag/hooks.py", line 87, in ensure_first_value
    single_val_lower = single_val.lower()
RuntimeError: AlbumInfo.raw_data failed: 'int' object has no attribute 'lower'
```

**Comment by snejus** [comment]
@sarteta are you planning to come back to this by any chance? We'd be glad to have this fixed!

**Comment by sarteta** [comment]
@snejus thanks for the patience and the suggested rewrite -- applied in 787d373.

Summary of the changes:
- Replaced the manual descriptor walk with `try: super().__getattribute__(attr)` and only intercept on `AttributeError` when the attribute resolves to a `cached_property`.
- Used `with_traceback(exc.__traceback__)` so the wrapped `RuntimeError` still points at the real failing line.
- `raise ... from None` to suppress the chained-cause block in CLI tracebacks (no more double traceback).
- Updated the regression tests in `test_hooks.py` accordingly: cause chain is now `None`, `__suppress_context__` is `True`, and the traceback we walk lives on the `RuntimeError` itself.
- Added a `Bug fixes` entry to the changelog under #6558.

Local: `pytest test/autotag/test_hooks.py` -> 92 passed.

**Review by snejus — APPROVED** [review]
Looks great, thanks!
