### ISSUE TITLE
Tarfile import fails with extraction failed: 'TarFile' object has no attribute 'infolist'

### ISSUE THREAD

**Issue by bcotton** [beetbox/beets#5664]
Seems `TarFile.infolist` was removed in Python 3: https://github.com/python/cpython/issues/47289#issuecomment-1093424447 when `ZipFileCompat` was removed from `TarFile`

introduced in https://github.com/beetbox/beets/pull/4396

### Problem

Running this command in verbose (`-vv`) mode:

```sh
beet -vv import -m Elton\ John\ -\ Your\ Songs\ \(1985\)\ \(flac\).tar-xpost/Elton_John_-_Your_Songs_\(1985\)_\(flac\).tar
```

Led to this problem:

```
user configuration: /home/bcotton/.config/beets/config.yaml
data directory: /home/bcotton/.config/beets
plugin paths:
library database: /media/music/musiclibrary.db
library directory: /media/music/curated
Sending event: library_opened
Sending event: import_begin
Extracting archive: /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
extraction failed: 'TarFile' object has no attribute 'infolist'
No files imported from /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux
* Python version: Python 3.12.8
* beets version:  master as of 2025-03-11
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: /media/music/curated
id3extract:
    mappings:
        WOAS: spotify_track_id

import:
    copy: yes
    move: no
# --------------- Main ---------------

library: /media/music/musiclibrary.db
musicbrainz:
    enabled: yes
    external_ids:
        bandcamp: yes
        beatport: yes
        deezer: yes
        discogs: yes
        spotify: yes
        tidal: yes
        youtube: yes
    extra_tags: []
    genres: yes
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1
    searchlimit: 5

# --------------- Plugins ---------------

plugins:
- spotify
- info
- fetchart
- lyrics
- lastgenre
- id3extract
spotify:
    mode: open
    region_filter: US
    show_failures: 'on'
    source_weight: 0
    tiebreak: first
    artist_field: albumartist
    album_field: album
    track_field: title
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: no
    keep_existing: no
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
lyrics:
    auto: yes
    translate:
        api_key: REDACTED
        from_languages: []
        to_language:
    dist_thresh: 0.11
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    print: no
    synced: no
    sources:
    - lrclib
    - google
    - genius
    - tekstowo

```
