### PR TITLE
Fix tar/7z archive import crashing with missing infolist() attribute

### LINKED ISSUE #5664: Tarfile import fails with extraction failed: 'TarFile' object has no attribute 'infolist'
Seems `TarFile.infolist` was removed in Python 3: https://github.com/python/cpython/issues/47289#issuecomment-1093424447 when `ZipFileCompat` was removed from `TarFile`

introduced in https://github.com/beetbox/beets/pull/4396

### Problem

Running this command in verbose (`-vv`) mode:

```sh
beet -vv import -m Elton\ John\ -\ Your\ Songs\ \(1985\)\ \(flac\).tar-xpost/Elton_John_-_Your_Songs_\(1985\)_\(flac\).tar
```

Led to this problem:

```
user configuration: /home/bcotton/.config/beets/config.yaml
data directory: /home/bcotton/.config/beets
plugin paths:
library database: /media/music/musiclibrary.db
library directory: /media/music/curated
Sending event: library_opened
Sending event: import_begin
Extracting archive: /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
extraction failed: 'TarFile' object has no attribute 'infolist'
No files imported from /media/music/downloads/lidarr/Elton John - Your Songs (1985) (flac).tar-xpost/Elton_John_-_Your_Songs_(1985)_(flac).tar
```

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Linux
* Python version: Python 3.12.8
* beets version:  master as of 2025-03-11
* Turning off plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: /media/music/curated
id3extract:
    mappings:
        WOAS: spotify_track_id

import:
    copy: yes
    move: no
# --------------- Main ---------------

library: /media/music/musiclibrary.db
musicbrainz:
    enabled: yes
    external_ids:
        bandcamp: yes
        beatport: yes
        deezer: yes
        discogs: yes
        spotify: yes
        tidal: yes
        youtube: yes
    extra_tags: []
    genres: yes
    host: musicbrainz.org
    https: no
    ratelimit: 1
    ratelimit_interval: 1
    searchlimit: 5

# --------------- Plugins ---------------

plugins:
- spotify
- info
- fetchart
- lyrics
- lastgenre
- id3extract
spotify:
    mode: open
    region_filter: US
    show_failures: 'on'
    source_weight: 0
    tiebreak: first
    artist_field: albumartist
    album_field: album
    track_field: title
    regex: []
    client_id: 4e414367a1d14c75a5c5129a627fcab8
    client_secret: REDACTED
    tokenfile: spotify_token.json
lastgenre:
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    source: album
    force: no
    keep_existing: no
    auto: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
lyrics:
    auto: yes
    translate:
        api_key: REDACTED
        from_languages: []
        to_language:
    dist_thresh: 0.11
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    print: no
    synced: no
    sources:
    - lrclib
    - google
    - genius
    - tekstowo

```

### PR DESCRIPTION
**Pull request by agu2347**
Fixes #5664.

`ArchiveImportTask.extract()` adjusts each extracted file's mtime after extraction by iterating `archive.infolist()` and reading each entry's `.filename` and `.date_time`. That's a `zipfile.ZipInfo`-specific interface. `tarfile.TarFile` used to also expose it via a `ZipFileCompat` shim, which was removed from the standard library; `py7zr.SevenZipFile` never had it either. Both raise `AttributeError: '...' object has no attribute 'infolist'` as soon as `extract()` reaches that loop, which the caller (`unarchive()`) catches and logs as `"extraction failed: ..."`, silently skipping the entire import -- exactly as reported in the issue.

**Fix**: handle `tarfile.TarFile` via its own `getmembers()`/`.name`/`.mtime` (`mtime` is already a Unix timestamp, unlike `ZipInfo.date_time`'s 6-tuple), and `py7zr.SevenZipFile` via its own `list()`/`.filename`/`.creationtime` (a timezone-aware `datetime`, converted via `.timestamp()`). `ZipFile` and `RarFile` (whose `infolist()` is intentionally zipfile-compatible, per `rarfile`'s own docs) keep using the existing path unchanged.

**A related discovery while verifying this**: while checking this fix against the project's own archive import tests (`TestImportTar`, `TestImportRar`, `TestImport7z`), I found those tests weren't actually exercising their respective archive formats at all. `TestImportZip.test_import_zip` called the module-level `create_archive()` free function directly rather than `self.create_archive()`, so Python's name resolution never dispatched to the `create_archive()` *method* that `TestImportTar`/`TestImportRar`/`TestImport7z` each override -- every one of those "format-specific" tests was silently creating and importing a plain zip file instead. This is why the `infolist()` bug (and, as I discovered while fixing this, the identical bug affecting 7z archives too) went undetected. Fixed by giving `TestImportZip` its own `create_archive()` method that calls the free function, and changing `test_import_zip` to call `self.create_archive()` so the override chain actually works. With that test-infra fix alone (`extract()` still unpatched), `TestImportTar` and `TestImport7z` now correctly fail with the exact reported `AttributeError`; with the `extract()` fix applied, both pass genuinely, actually exercising tar/7z extraction for the first time.

**Verification**: verified end-to-end with real archives: a real `.tar` file no longer raises and correctly preserves each extracted file's original mtime; same for a real `.7z` archive (installed `py7zr` to confirm, since it isn't a required dependency); confirmed `.zip` extraction is completely unaffected (unchanged code path, verified with a real `.zip` round-trip too). RAR extraction code path is untouched by this fix (still uses the original `infolist()` branch, since `RarFile` intentionally mimics zipfile's interface); `TestImportRar` remains skipped in my sandbox only because the `unrar` binary isn't detected there, unrelated to this change.

Ran the full existing `test_importer.py` suite: 132 passed, 5 skipped (unrelated: missing `unrar` binary, three pre-existing "write me"/"Implement me" stubs, one needing reflink support), no regressions.

### CODE REVIEW

**Comment by semohr** [comment]
I fail to understand the reasoning behind opening a number of PRs in different open source projects using an AI agent. What do you gain here?

Please see our guidelines on AI usage.
