### ISSUE TITLE
Musicbrainz genres deleted using `mbsync` after https://github.com/beetbox/beets/pull/6401

### ISSUE THREAD

**Issue by aereaux** [beetbox/beets#6403]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vvv mbsync Copland
user configuration: /home/user/.config/beets/config.yaml
data directory: /home/user/.config/beets
plugin paths: ['/home/user/.config/beets/plugins']
Loading plugins: chroma, convert, edit, fetchart, fish, info, inline, listenbrainz, m3ufixer, mbcollection, mbsync, musicbrainz, parentwork, play, scrub, smartplaylist
/home/user/.local/share/uv/tools/beets/lib/python3.14/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
inline: adding item field mpd_path
inline: adding album field mb_albumurl
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
Sending event: pluginload
library database: /home/user/.config/beets/library.db
library directory: /home/user/music/beets
Sending event: library_opened
Parsed query: AndQuery([OrQuery([SubstringQuery('artist', 'Copland', fast=True), SubstringQuery('title', 'Copland', fast=True), SubstringQuery('comments', 'Copland', fast=True), SubstringQuery('album', 'Copland', fast=True), SubstringQuery('albumartist', 'Copland', fast=True), SubstringQuery('genres', 'Copland', fast=True)]), NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([OrQuery([SubstringQuery('album', 'Copland', fast=True), SubstringQuery('albumartist', 'Copland', fast=True), SubstringQuery('genres', 'Copland', fast=True)])])
Parsed sort: NullSort()
musicbrainz: Requesting MusicBrainz release 192a76ff-b05a-4988-9f0a-bc095d44fcd3
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
mbsync: applying changes to Samuel Barber, Charles Ives, Aaron Copland; Academy of St Martin in the Fields, Sir Neville Marriner - Barber: Adagio for Strings / Ives: Symphony no. 3 / Copland: Quiet City
musicbrainz: Requesting MusicBrainz release a881c055-6d9a-4abb-8e5f-63107797e7d4
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
mbsync: applying changes to Béla Bartók, Leonard Bernstein, Aaron Copland, Morton Gould, Игорь Фёдорович Стравинский; Benny Goodman - Benny Goodman Collector's Edition: Compositions & Collaborations
Béla Bartók - Benny Goodman Collector's Edition: Compositions & Collaborations - Contrasts: I. Verbunkos (Recruiting Dance)
  genres:
    - classical
    - jazz
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
m3ufixer: Building m3u cache...
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Béla Bartók - Benny Goodman Collector's Edition: Compositions & Collaborations - Contrasts: II. Pihenö (Relaxation)
  genres:
    - classical
    - jazz
[...]
```

Led to this problem:

The genres are being removed

Here's a link to the music files that trigger the bug (if relevant):

### Setup

* OS: Arch Linux
* Python version: 3.14.3
* beets version: 573dca687a94606fbd4683c882a946e0a36ce5c5
* Turning off plugins made problem go away (yes/no): N/A (needs musicbrainz plugin)

My configuration (output of `beet config`) is:

```yaml
[...]
musicbrainz:
    genres: yes
[...]
```

It looks like the genres are still being received in the musicbrainz plugin, and being set in `info.genres`, but something might be happening after this.

**Comment by aereaux** [comment]
I tried to bisect, but there are some revisions that error:
```
/home/user/.local/share/uv/tools/beets/lib/python3.14/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/.local/bin/beet", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/.local/lib/beets/beets/ui/__init__.py", line 1633, in main
    _raw_main(args)
    ~~~~~~~~~^^^^^^
  File "/home/user/.local/lib/beets/beets/ui/__init__.py", line 1608, in _raw_main
    subcommands, lib = _setup(options, lib)
                       ~~~~~~^^^^^^^^^^^^^^
  File "/home/user/.local/lib/beets/beets/ui/__init__.py", line 1445, in _setup
    lib = _open_library(config)
  File "/home/user/.local/lib/beets/beets/ui/__init__.py", line 1505, in _open_library
    lib = library.Library(
        dbpath,
    ...<2 lines>...
        get_replacements(),
    )
  File "/home/user/.local/lib/beets/beets/library/library.py", line 33, in __init__
    super().__init__(path, timeout=timeout)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/beets/beets/dbcore/db.py", line 1130, in __init__
    self._migrate()
    ~~~~~~~~~~~~~^^
  File "/home/user/.local/lib/beets/beets/dbcore/db.py", line 1348, in _migrate
    migration.migrate_table(model_cls._table)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/beets/beets/dbcore/db.py", line 1060, in migrate_table
    if not self.db.migration_exists(self.name, table):
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/beets/beets/dbcore/db.py", line 1353, in migration_exists
    return tx.execute(
           ^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'execute'
$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
4dda8e3e49489f0b1b6e83dbc9a35d9fbc85e0a4
cf36ed07546d78c27df6d1d4d57ebda0d1750be6
2ecbe59f48ddc07bc9ba31c8c16102442ef7870f
b8f1b9d174afb353b93e7ee3f04c31cb40fdd796
5d7fb4e1586c5fa5c4e79a6010dd65ca37e3c37b
We cannot bisect more!
```

**Comment by snejus** [comment]
I can reproduce, see

<img width="584" height="524" alt="Image" src="https://github.com/user-attachments/assets/47858d38-8b32-484e-bbdb-2c1320ad4094" />

It seems like the behaviour is not limited to `genres` field only, mbsync also clears my `album` tags too.

**Comment by snejus** [comment]
Apologies regarding `bisect` - seems like I wasn't too careful regarding my commits and there are several broken commits where `execute` method was not present which I later removed.

**Comment by aereaux** [comment]
Yeah, I'm stumped here, I'm not sure what in the diff between the good and bad commits could be causing this.  Could it be related to the dbcore changes?

**Comment by aereaux** [comment]
I did a bit more debugging, and it looks like with the old code it sets the genre field in the track info items in `MBSyncPlugin.items()`, but it doesn't with the new code.  I'm not sure why that is though.

**Comment by snejus** [comment]
Seems like the plugin only applies track-level fields:

```py
            track_index = defaultdict(list)
            print(album_info.genres)
            for track_info in album_info.tracks:
                print(track_info.genres)
```

```
$ beet mbsync data_source:brainz eminem
['hip hop', 'conscious hip hop', 'pop rap', 'hardcore hip hop', 'gangsta rap']
[]
[]
[]
57430 | 2002 / Lose Yourself: Eminem - Lose Yourself
  album: Lose Yourself -> 
  genres:
    - conscious hip hop
    - gangsta rap
    - hardcore hip hop
    - pop rap
    - rap rock
```

**Comment by snejus** [comment]
Actually, the issue is in `_apply_metadata` function which did not take into account empty multi-valued fields. The fix:

```diff
diff --git a/beets/autotag/__init__.py b/beets/autotag/__init__.py
index feeefbf28..e6be9d1a1 100644
--- a/beets/autotag/__init__.py
+++ b/beets/autotag/__init__.py
@@ -127,7 +127,7 @@ def _apply_metadata
 
         # Don't overwrite fields with empty values unless the
         # field is explicitly allowed to be overwritten.
-        if value is None and field not in nullable_fields:
+        if (value is None or value == []) and field not in nullable_fields:
             continue
 
         db_obj[field] = value
```

**Comment by snejus** [comment]
Now need to figure out where does the `album` field get lost

**Comment by snejus** [comment]
Ah, `album` was NULLed on my end because I had

```yaml
overwrite_null:
  track:
    - album
```

in my configuration.

**Comment by djl** [comment]
This still seems to be happening for me:

```
$ bq ls -a -f '$album - $genres' tryra
Tryra - deep techno
$ bq -vvv mbsync -p tryra
user configuration: /home/djl/.config/beets/config.yaml
data directory: /home/djl/.config/beets
plugin paths: ['/home/djl/.config/beets/plugins']
Loading plugins: artwork, catalog, checkcredits, checkdirs, checkflacs, checkmpd, checkpaths, checks, convert, copyartifacts, downsampler, dupes, fetchart, findreplace, fuzzy, genres, headphones, importfeeds, info, inline, limit, mbcollections, mbopenurl, mborphans, mbsync, mbtpg, mbtrackutils, missing, missingfiles, missingreleases, musicbrainz, orphans, querystore, scrub, templateutils, timedelta, types, upgrades, wipe, zero
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
genres: Skipping disabled fetcher: lastfm
inline: adding item field multidisc
inline: adding item field disc_unpadded
inline: adding item field disc_smartpadded
inline: adding item field added_simple
inline: adding album field bitrate
inline: adding album field bitdepth
inline: adding album field date
inline: adding album field all_formats
inline: adding album field all_media
inline: adding album field filesize
inline: adding album field mburl
inline: adding album field mbgurl
inline: adding album field disambigs
inline: adding album field years
inline: adding album field brlabel
Sending event: pluginload
library database: /home/djl/var/beets/library.db
library directory: /data/media/audio/music
Sending event: library_opened
Parsed query: AndQuery([OrQuery([SubstringQuery('artist', 'tryra', fast=True), SubstringQuery('title', 'tryra', fast=True), SubstringQuery('comments', 'tryra', fast=True), SubstringQuery('album', 'tryra', fast=True), SubstringQuery('albumartist', 'tryra', fast=True), SubstringQuery('genres', 'tryra', fast=True)]), NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([OrQuery([SubstringQuery('album', 'tryra', fast=True), SubstringQuery('albumartist', 'tryra', fast=True), SubstringQuery('genres', 'tryra', fast=True)])])
Parsed sort: NullSort()
musicbrainz: Requesting MusicBrainz release 7121ed80-d6b6-4f85-baf8-6035dd334209
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
mbsync: applying changes to Daniel[i] - Tryra
Sending event: album_matched
Daniel[i] - Tryra - Hegrei
  genres:
    - deep techno
Daniel[i] - Tryra - Prahi
  genres:
    - deep techno
Daniel[i] - Tryra - Sgyro
  genres:
    - deep techno
Daniel[i] - Tryra - Tryra
  genres:
    - deep techno
Sending event: cli_exit
Sending event: artifacts_copied
```

I'm definitely up to date with beets also:

```
prj/beets@master% git rev-parse HEAD
72b4c771612df3dbaee56c4460fe76297ddf9a87
```

**Comment by aereaux** [comment]
> This still seems to be happening for me:

What is your config?  And this happens with other albums in your library?

**Comment by djl** [comment]
> > This still seems to be happening for me:
> 
> What is your config? And this happens with other albums in your library?

This happens with any album with genres in my library. Here's a few from this week:

```
~% bq mbsync -p Wil Bolton Barbican
Wil Bolton - Barbican - The Yellow Line
  genres:
    - ambient
Wil Bolton - Barbican - Lost on the Highwalk
  genres:
    - ambient
Wil Bolton - Barbican - The Circle Below
  genres:
    - ambient
Wil Bolton - Barbican - Turquoise Artifice
  genres:
    - ambient
Wil Bolton - Barbican - Frobisher Crescent
  genres:
    - ambient
~% bq mbsync -p Ancient Astronaut Inner Worlds
Ancient Astronaut - Inner Worlds - Expanding Worlds
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Between Worlds
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Transe Lucide
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Shimmering Crystals
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Catalystic Mind
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Blue Lineage
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Waves of Blue
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Floating Orbs
  genres:
    - ambient
Ancient Astronaut - Inner Worlds - Inner Worlds
  genres:
    - ambient
```

Relevant part of my config:

```
musicbrainz:
    user: REDACTED
    pass: REDACTED
    extra_tags: [alias]
    search_limit: 5
    data_source_mismatch_penalty: 0.5
    search_query_ascii: no
    genres: no
    genres_tag: genre
    external_ids:
        discogs: no
        bandcamp: no
        spotify: no
        deezer: no
        tidal: no
import:
    copy: no
    move: yes
    timid: yes
    write: yes
    from_scratch: yes
    languages: [en]
    ignored_alias_types: [legal name]


plugins:
- genres
- musicbrainz
- smarterplaylist
- sonic
- templateutils
- timedelta
- types
- zero

overwrite_null:
    album:
    - albumdisambig
    - albumstatus
    - albumtype
    - asin
    - catalognum
    - country
    - label
    - language
    - releasegroupdisambig
    - script
    track:
    - arranger
    - composer
    - composer_sort
    - disctitle
    - lyricist
    - media
    - trackdisambig
    - work_disambig
```

I should point out that I fetch my genres with a custom plugin. It's effectively just the musicbrainz plugin but only fetching my own tags/genres for a specific release or group.

**Comment by aereaux** [comment]
Ah, I see.  Do you need to make any changes to your plugin to account for the changed tag (`genre` vs `genres`)?

**Comment by djl** [comment]
> Ah, I see. Do you need to make any changes to your plugin to account for the changed tag (`genre` vs `genres`)?

Sadly not. I updated my plugin right after that change landed.

**Comment by djl** [comment]
OK, so I figured it out. If you set `musicbrainz.genres` to `False`, it will strip _all_ existing genres.

That seems counterintuitive to me. If `musicbrainz.genres` is `False` then I would expect it to ignore that field entirely, not irreversibly delete data.

Is there no way to have that tag ignored by the plugin?

If not, I may submit a PR to allow this and only fetch personal tags/genres. Then I can get rid of my own plugin 😁

**Comment by snejus** [comment]
Thanks for investigating this @djl! Please do submit a PR to fix this, I will happily review it :)

**Comment by snejus** [comment]
@aereaux @djl what are your `overwrite_null` configurations?

**Comment by aereaux** [comment]
I do not have that option set.

**Comment by snejus** [comment]
Is this issue still happening for you @aereaux ?

**Comment by aereaux** [comment]
My issue (the original one I reported) was fixed by https://github.com/beetbox/beets/pull/6405.  I never experienced the other issue that @djl reported because I use the musicbrainz genres functionality instead of setting them elsewhere.

**Comment by djl** [comment]
> [@djl](https://github.com/djl) what are your `overwrite_null` configurations?

```
overwrite_null:
    album:
    - albumdisambig
    - albumstatus
    - albumtype
    - asin
    - catalognum
    - country
    - label
    - language
    - releasegroupdisambig
    - script
    track:
    - arranger
    - composer
    - composer_sort
    - disctitle
    - lyricist
    - media
    - trackdisambig
    - work_disambig
 ```

**Comment by snejus** [comment]
Under https://github.com/beetbox/beets/pull/6513 we found that the issue was with @djl configuration. This issue has been fixed by the previously linked PR.
