### PR TITLE
fix #3685

### LINKED ISSUE #3685: Sanitize colons in drive-letter-like positions in Windows filenames like path separators
I have an album containing an artist named "F:A.R.". When doing any activity that involves moving this artist, the file is not moved to "M:\F:A.R." (I'm using unicode replacements instead of underscores), but to "M:\F:\A.R.".

### Problem

Running this command in verbose (`-vv`) mode:

```sh
~ ❯ beet -vv move "artist::^F.A.R"
user configuration: C:\Users\Gunther Schmidl\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Gunther Schmidl\AppData\Roaming\beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
library database: M:\lib.db
library directory: M:\
Sending event: library_opened
Moving 1 item.
moving: M:\F꞉A․R․ ／ Muslimgauze\[1990] Manipulation (Live Extracts) ／ Death of Saint Jarnaii Singh Bhindranwaie\01-01 - Manipulation (Live Extracts).mp3
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: cli_exit
```

Led to this problem:

Here's what it looks like in the database: https://i.imgur.com/Z5lvGqE.png

Here's a link to the music files that trigger the bug (if relevant):

https://www.dropbox.com/s/pastihu349z6kce/01-01%20-%20Manipulation%20%28Live%20Extracts%29.mp3?dl=0

### Setup

* OS: Windows 10 v2004
* Python version: 3.8.0
* beets version: latest trunk, but also happens in latest released version
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
lyrics:
    bing_lang_from: []
    auto: yes
    bing_client_secret: REDACTED
    bing_lang_to:
    google_API_key: REDACTED
    google_engine_ID: REDACTED
    genius_api_key: REDACTED
    fallback:
    force: no
    local: no
    sources:
    - google
    - lyricwiki
    - musixmatch
    - genius
directory: M:/
library: M:/lib.db

paths:
    default: $albumartist/[$year] $album%aunique{}/$disc-$track - $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/[$year] $album%aunique{}/$disc-$track - $title

plugins: web mbsync discogs chroma lastgenre duplicates lyrics
lastgenre:
    source: artist
    force: no
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    auto: yes
    separator: ', '
    prefer_specific: no

replace:
    \\: "\uFF3C"
    /: "\uFF0F"
    \.{3}: "\u2026"
    \.: "\u2024"
    '[\x00-\x1f]': ''
    <: "\uFE64"
    '>': "\uFE65"
    ':': "\uA789"
    '"': "\uFF02"
    \?: "\uFF1F"
    \*: "\u204E"
    \|: "\u2502"
    \s+$: ''
    ^\s+: ''
    ^-: "\u2012"
path_sep_replace: "\uFF0F"
discogs:
    apikey: REDACTED
    apisecret: REDACTED
    tokenfile: discogs_token.json
    source_weight: 0.5
    user_token: REDACTED
    separator: ', '
    index_tracks: no
web:
    host: 127.0.0.1
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
duplicates:
    album: no
    checksum: ''
    copy: ''
    count: no
    delete: no
    format: ''
    full: no
    keys: []
    merge: no
    move: ''
    path: no
    tiebreak: {}
    strict: no
    tag: ''
chroma:
    auto: yes
```

### PR DESCRIPTION
**Pull request by gschmidl**
## Description

Fixes #3685.  

Could probably be improved if you care about it being Windows-only. Works for now - maybe someone else has a use for it even if you don't use it.

## To Do

- [ ] Documentation: new flag drive_sep_replace, defaults to '_'
- [ ] Changelog. (Add an entry to `docs/changelog.rst` near the top of the document.)

### CODE REVIEW

**Comment by gschmidl** [comment]
Man this is embarrassing. Tox doesn't work locally and I have next to no experience in Python.

**Comment by jtpavlock** [comment]
If you're on windows, you may have to install tox 3.8.3 `python -m pip install tox=3.8.3` per [this issue](https://github.com/tox-dev/tox/issues/1550#issuecomment-661381136)

**Comment by jtpavlock** [comment]
Also, would you be willing to write a test to double check this fixes the issue, and that it won't pop back up in the future?

**Comment by gschmidl** [comment]
I can try! I tested it against the file, of course, and that seemed to work.

File: beets/dbcore/db.py [hunk 1]
```diff
@@ -84,6 +85,10 @@ def _get_formatted(self, model, key):
 
         if self.for_path:
             sep_repl = beets.config['path_sep_replace'].as_str()
+            sep_drive = beets.config['drive_sep_replace'].as_str()
+            if re.match(r'^\w:', value):
+                value = value.replace(':', sep_drive)
```
Comment (sampsyo) [inline beets/dbcore/db.py:90]: This is a little broad, for what it's worth: it will replace _all_ occurrences of `:`, where the only one we really need to replace is the first one. A positive lookbehind assertion might do the trick:

```py
>>> re.sub(r'(?<=^\w):', '_', 'f:o:o')
'f_o:o'
```

Comment (gschmidl) [reply beets/dbcore/db.py:90]: Got it, I'll change that and add the extra test - however, the tests don't seem to be working on Python 2.7 :(

Comment (sampsyo) [reply beets/dbcore/db.py:90]: Indeed; the error is this: `AttributeError: 'MoveTest' object has no attribute 'assertRegex'`

But I don't think that test needs `assertRegex`, and `assertEqual` or `assertIn` might suffice?

Comment (gschmidl) [reply beets/dbcore/db.py:90]: Will the normal replacements be applied during move()? If so, that colon is getting replaced anyway.

Comment (gschmidl) [reply beets/dbcore/db.py]: That seems to have done it.

File: test/test_files.py [hunk 2]
```diff
@@ -102,6 +102,25 @@ def test_move_already_at_destination(self):
         self.i.move()
         self.assertEqual(self.i.path, old_path)
 
+    def test_move_file_with_colon(self):
```
Comment (jtpavlock) [inline test/test_files.py:105]: Do these test cases reproduce the original problem (without the fix coded in)?

Comment (gschmidl) [reply test/test_files.py:105]: test_move_file_with_colon reproduces the original problem, yes:

```
self = <test.test_files.MoveTest testMethod=test_move_file_with_colon>

    def test_move_file_with_colon(self):
        self.i.artist = u'C:DOS'
        self.i.move()
>       self.assertIn('C_DOS', self.i.path.decode())
E       AssertionError: 'C_DOS' not found in 'C:\\Users\\GUNTHE~1\\AppData\\Local\\Temp\\tmpcmwnupd6\\testlibdir\\C_\\DOS\\two\\three.mp3'
```

The other two don't because their setup eschews the original problem.

Comment (jtpavlock) [reply test/test_files.py:105]: Awesome, thanks for that. Since I don't program on Windows, I've been trying to find a good way to reproduce stuff like this.

**Comment by gschmidl** [comment]
> Awesome; thank you! I think all we need here is a changelog entry and it's ready to merge.

Do you want me to add it, or will you?

**Comment by sampsyo** [comment]
Please go for it, @gschmidl, if you don't mind.

**Comment by sampsyo** [comment]
Wonderful; thank you!!

**Comment by gschmidl** [comment]
> Wonderful; thank you!!

I hope it's ok that I'm not thanking myself, that just feels weird :)
